title: Escola 4.0
email: contato@escola4pontozero.com.br
description: ""
baseurl: ""
url: ""
twitter_username:
github_username:
instagram_username: escola4.0
youtube_username: 
facebook_username: Escola-40-113220510212473

# Build settings
theme: minima
permalink: /blog/:title
plugins:
  - jekyll-feed

sass:
    style: compressed

collections:
  team:
    sort_by: number
  sponsors:
  slides:
  courses: